apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: chirp-prod
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
