apiVersion: batch/v1
kind: Job
metadata:
  name: messaging-migrate
  namespace: chirp-prod
  labels:
    app: messaging
spec:
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: messaging-migrate
          image: chirp/messaging:latest
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: chirp-config
            - secretRef:
                name: chirp-secrets
          env:
            - name: SERVICE_NAME
              value: "messaging-service"
            - name: PORT
              value: "8008"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chirp-secrets
                  key: DATABASE_URL_MESSAGING
      workingDir: /srv/service
      restartPolicy: Never
  backoffLimit: 3
