"""Declarative base and common column mixins.

Every service defines its own models against this base. There is deliberately
no shared model module: two services never import each other's tables. Cross
service references are stored as plain id strings with no foreign key, because
the referenced row lives in a different database.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from chirp_common.ids import ULID_LENGTH, new_ulid


class Base(DeclarativeBase):
    """Base class for all ORM models."""


class ULIDPrimaryKeyMixin:
    """Time-sortable string primary key generated by the application."""

    id: Mapped[str] = mapped_column(
        String(ULID_LENGTH), primary_key=True, default=new_ulid
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Soft deletion for rows other services may still reference.

    Posts and users are soft-deleted: a reply, notification or timeline entry
    in another service points at the id, and hard deletion would leave those
    unable to distinguish "gone" from "never existed". Rows that nothing else
    references (bookmarks, mutes, likes) are hard-deleted instead.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None
