"""Sortable identifiers.

Chirp uses ULIDs (128-bit, 48-bit millisecond timestamp + 80 random bits)
rendered as 26-character Crockford base32 strings.

Why not auto-increment integers: ids are generated by the owning service and
travel across service boundaries in events, so they must be globally unique
without a shared sequence.

Why not UUIDv4: timelines, replies and messages are read in creation order.
Lexicographic ULID ordering matches creation order, which makes keyset
(cursor) pagination a plain `WHERE id < :cursor ORDER BY id DESC` and keeps
btree inserts roughly append-only instead of scattering across the index.
"""

from __future__ import annotations

import os
import time

_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"  # Crockford base32, no I L O U
_DECODE = {c: i for i, c in enumerate(_ALPHABET)}
ULID_LENGTH = 26


def new_ulid(timestamp_ms: int | None = None) -> str:
    """Generate a new ULID string."""
    ts = int(time.time() * 1000) if timestamp_ms is None else timestamp_ms
    value = (ts << 80) | int.from_bytes(os.urandom(10), "big")
    return _encode(value, ULID_LENGTH)


def ulid_timestamp_ms(value: str) -> int:
    """Extract the embedded millisecond timestamp from a ULID."""
    return _decode(value) >> 80


def is_ulid(value: str) -> bool:
    if len(value) != ULID_LENGTH:
        return False
    return all(c in _DECODE for c in value.upper())


def _encode(value: int, length: int) -> str:
    chars = []
    for _ in range(length):
        chars.append(_ALPHABET[value & 0x1F])
        value >>= 5
    return "".join(reversed(chars))


def _decode(value: str) -> int:
    result = 0
    for char in value.upper():
        try:
            result = (result << 5) | _DECODE[char]
        except KeyError as exc:  # pragma: no cover - defensive
            raise ValueError(f"invalid ULID character: {char!r}") from exc
    return result

