apiVersion: v1
kind: Service
metadata:
  name: post-svc
  namespace: chirp-prod
  labels:
    app: post
spec:
  type: ClusterIP
  selector:
    app: post
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
