apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: chirp-prod
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
