apiVersion: v1
kind: Secret
metadata:
  name: chirp-secrets
  namespace: chirp-prod
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_openssl_rand_hex_32"
  POSTGRES_PASSWORD: "REPLACE_WITH_openssl_rand_hex_16"
  REDIS_AUTH_TOKEN: ""
  DATABASE_URL_AUTH: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_auth"
  DATABASE_URL_USER: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_user"
  DATABASE_URL_POST: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_post"
  DATABASE_URL_GRAPH: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_graph"
  DATABASE_URL_TIMELINE: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_timeline"
  DATABASE_URL_SEARCH: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_search"
  DATABASE_URL_NOTIFICATION: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_notification"
  DATABASE_URL_MESSAGING: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_messaging"
  DATABASE_URL_MEDIA: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_media"
  DATABASE_URL_MODERATION: "postgresql+asyncpg://chirp_admin:REPLACE@REPLACE:5432/chirp_moderation"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_BUCKET: "chirp-prod-media"
